// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://merjfjpiqppjhdasvyvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lcmpmanBpcXBwamhkYXN2eXZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzM2MDAsImV4cCI6MjA3MTAwOTYwMH0.MKSK5ySVqYj8yLSpJM4t-2mpFica8nj-dGdH8PwrqcM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});